### ISSUE TITLE
ImportError: No module named utils on Windows 8.1

### ISSUE THREAD

**Issue by snowuyl** [Asoul/tsrtc#4]
Dear Asoul,

```
    I run crawl.py with Python 2.7.12.  But the following error occurred.
```

C:\workspace_Python\tsrtc>python crawl.py
Traceback (most recent call last):
  File "crawl.py", line 8, in <module>
    import requests
  File "c:\Python27\lib\site-packages\requests__init__.py", line 60, in <module

> ```
> from .packages.urllib3.exceptions import DependencyWarning
> ```
> 
>   File "c:\Python27\lib\site-packages\requests\packages__init__.py", line 29, i
> n <module>
>     import urllib3
>   File "c:\Python27\lib\site-packages\urllib3__init__.py", line 8, in <module>
>     from .connectionpool import (
>   File "c:\Python27\lib\site-packages\urllib3\connectionpool.py", line 35, in <m
> odule>
>     from .request import RequestMethods
>   File "c:\Python27\lib\site-packages\urllib3\request.py", line 3, in <module>
>     from .filepost import encode_multipart_formdata
>   File "c:\Python27\lib\site-packages\urllib3\filepost.py", line 9, in <module>
>     from .fields import RequestField
>   File "c:\Python27\lib\site-packages\urllib3\fields.py", line 2, in <module>
>     import email.utils
> ImportError: No module named utils

Do you have any suggestion?

Thanks in advance!

snowuyl

**Comment by snowuyl** [comment]
I have fixed this issue by rename email.py to gmail.py.
